syscfg.vals:
    OS_CRASH_FILE_LINE: 1
    MSYS_1_BLOCK_SIZE: 308

    BLE_VERSION: 60
    BLE_EXT_ADV: 1
    BLE_EXT_ADV_MAX_SIZE: 1650
    BLE_PERIODIC_ADV: 1
    BLE_PERIODIC_ADV_SYNC_TRANSFER: 1
    BLE_POWER_CONTROL: 1
    BLE_MULTI_ADV_INSTANCES: 4
    BLE_MAX_PERIODIC_SYNCS: 4
    BLE_MAX_CONNECTIONS: 4

    BLE_TRANSPORT_ACL_COUNT: 32
    BLE_TRANSPORT_ACL_SIZE: 255
    BLE_TRANSPORT_EVT_COUNT: 4
    BLE_TRANSPORT_EVT_DISCARDABLE_COUNT: 64
    BLE_TRANSPORT_ISO_COUNT: 32
    BLE_TRANSPORT_ISO_SIZE: 256

syscfg.vals.BLE_CONTROLLER:
    BLE_LL_STACK_SIZE: 200
    BLE_LL_CFG_FEAT_DATA_LEN_EXT: 1
    BLE_LL_CFG_FEAT_LE_2M_PHY: 1
    BLE_LL_CFG_FEAT_LE_CODED_PHY: 1
    BLE_LL_CFG_FEAT_LL_PRIVACY: 1
    BLE_LL_CFG_FEAT_LL_SCA_UPDATE: 1
    BLE_LL_CFG_FEAT_LL_ENHANCED_CONN_UPDATE: 1
    BLE_LL_CFG_FEAT_CTRL_TO_HOST_FLOW_CONTROL: 1
    BLE_LL_CFG_FEAT_LL_PERIODIC_ADV_ADI_SUPPORT: 1
    BLE_LL_CONN_PHY_INIT_UPDATE: 1
    BLE_LL_HCI_VS_EVENT_ON_ASSERT: 1
    BLE_LL_DTM: 1
    BLE_LL_CONN_INIT_SLOTS: 1
    BLE_LL_SCAN_AUX_SEGMENT_CNT: 16
    BLE_LL_NUM_SCAN_DUP_ADVS: 64
#    BLE_LL_SCHED_AUX_CHAIN_MAFS_DELAY: 30
    BLE_LL_PERIODIC_ADV_SYNC_BIGINFO_REPORTS: 1
    BLE_LL_ISO: 1
    BLE_LL_ISO_BROADCASTER: 1
